
export const COUNTRY_TIMEZONES: Record<string, string> = {
  "USA": "America/New_York",
  "CAN": "America/Toronto",
  "MEX": "America/Mexico_City",
  "BRA": "America/Sao_Paulo",
  "ARG": "America/Argentina/Buenos_Aires",
  "GBR": "Europe/London",
  "FRA": "Europe/Paris",
  "DEU": "Europe/Berlin",
  "ESP": "Europe/Madrid",
  "ITA": "Europe/Rome",
  "RUS": "Europe/Moscow",
  "CHN": "Asia/Shanghai",
  "JPN": "Asia/Tokyo",
  "IND": "Asia/Kolkata",
  "AUS": "Australia/Sydney",
  "ZAF": "Africa/Johannesburg",
  "EGY": "Africa/Cairo",
  "NGA": "Africa/Lagos",
  "SAU": "Asia/Riyadh",
  "TUR": "Europe/Istanbul",
  "KOR": "Asia/Seoul",
  "IDN": "Asia/Jakarta",
  "THA": "Asia/Bangkok",
  "VNM": "Asia/Ho_Chi_Minh",
  "COL": "America/Bogota",
  "CHL": "America/Santiago",
  "PER": "America/Lima",
  // Removed duplicate "ESP" entry from line 30
  "PRT": "Europe/Lisbon",
  "GRC": "Europe/Athens",
  "UKR": "Europe/Kyiv",
  "POL": "Europe/Warsaw",
  "NOR": "Europe/Oslo",
  "SWE": "Europe/Stockholm",
  "FIN": "Europe/Helsinki",
  "NZL": "Pacific/Auckland",
  "PHL": "Asia/Manila",
  "MYS": "Asia/Kuala_Lumpur",
  "SGP": "Asia/Singapore",
  "PAK": "Asia/Karachi",
  "BGD": "Asia/Dhaka",
  "IRN": "Asia/Tehran",
  "IRQ": "Asia/Baghdad",
  "ISR": "Asia/Jerusalem",
  "MAR": "Africa/Casablanca",
  "KEN": "Africa/Nairobi",
  "ETH": "Africa/Addis_Ababa",
};

// Fallback lookup by common names if ID (ISO3) fails
export const NAME_TO_ISO: Record<string, string> = {
  "United States of America": "USA",
  "Brazil": "BRA",
  "Canada": "CAN",
  "Russia": "RUS",
  "China": "CHN",
  "Australia": "AUS",
  "India": "IND",
  "Japan": "JPN",
  "United Kingdom": "GBR",
  "France": "FRA",
  "Germany": "DEU",
  "Italy": "ITA",
  "Spain": "ESP",
  "Mexico": "MEX",
  "Argentina": "ARG",
  "South Africa": "ZAF",
  "Nigeria": "NGA",
  "Egypt": "EGY",
  "South Korea": "KOR",
  "Indonesia": "IDN",
  "Saudi Arabia": "SAU",
  "Turkey": "TUR",
  "Israel": "ISR",
  "Vietnam": "VNM",
  "Thailand": "THA",
  "Poland": "POL",
  "Ukraine": "UKR",
  "Colombia": "COL",
  "Peru": "PER",
  "Chile": "CHL",
};
